### ISSUE TITLE
TNT carts to kill players

### ISSUE THREAD

**Issue by IAMSOEPIC2303** [ChanceSD/PvPManager#502] opened 2024-06-03 21:14 UTC

**Comment by IAMSOEPIC2303** [comment] 2024-06-03 21:14
tnt carts kill players in disable pvp

**Comment by IAMSOEPIC2303** [comment] 2024-06-03 21:14
im not gonna respond to this bci just wanted an acc to comment on the bug. please fix it

**Comment by IAMSOEPIC2303** [comment] 2024-06-04 09:28
Why the hell remove from bugs. It’s a damn big. People abuse the damn mute carts to kill ppl

**Comment by ChanceSD** [comment] 2024-06-04 12:54
Because it's not a bug.

**Comment by ChanceSD** [comment] 2024-07-05 07:43
Won't be adding this to free version, it's already on premium since last year.

**Closed by ChanceSD** 2024-07-05 07:43 UTC
Labels: enhancement
